#!/bin/sh
_thisdir=$(cd $(dirname $0); pwd)

cron() {
    [ $1 ] && sleep $1

    i=0
    while true
    do
        [ -x "$(which feh 2> /dev/null)" ] && [ $((i % 300)) -eq 0 ]\
            && feh --randomize --bg-fill $wallpapers/*.png

        sleep 2; i=$((i + 2))
    done
}

startup() {
    [ $1 ] && sleep $1

    [ -x "$(which st 2> /dev/null)" ]\
        && st -e tmux &
}

cron &
startup &
