#!/bin/sh
_thisdir=$(cd $(dirname $0); pwd)

check() {
  apps=('dunst' 'feh' 'picom' 'fcitx5' 'st' 'tmux' 'xbanish' 'lf')
  files=("$HOME/.Xmodmap" "$wallpaper")
  for i in ${apps[*]} ${files[*]}
  do
    if ls '/bin/'$i &>/dev/null || ls $i &>/dev/null
    then
      echo &>/dev/null
    else
      exit
    fi
  done
}

statusbar() {
  xsetroot -name "$(date '+%Y-%m-%d %H:%M')"
}

cron() {
  i=0
  while true
  do
    [ $((i % 300)) -eq 0 ] && feh --randomize --bg-fill $wallpapers/*.png
    [ $((i % 2)) -eq 0 ] && statusbar
    sleep 2; i=$((i + 2))
  done
}

startup() {
  st -e tmux &
}

daemons() {
  picom -b &
  xbanish -m se&
  dunst &
  fcitx5 -d 2> /dev/null &
  lf -server &
}

check
cron &
daemons &
startup &
